services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AUS\MetricsExporter\:
    resource: '../Classes/*'

  AUS\MetricsExporter\Service\CollectorService:
    public: true

  cache.prometheus_storage:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'prometheus_storage' ]
    tags:
      - { name: cache, identifier: 'prometheus_storage', immutable: true }

  AUS\MetricsExporter\EventListener\PrometheusExporterProxyEventListener:
    tags:
      - name: event.listener
        identifier: 'aus-metrics/prometheus-exporter-proxy'
        event: AUS\MetricsExporter\Event\WriteStreamEvent

  AUS\MetricsExporter\EventListener\PrometheusFpmEventListener:
    tags:
      - name: event.listener
        identifier: 'aus-metrics/prometheus-fpm'
        event: AUS\MetricsExporter\Event\WriteStreamEvent
